name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  example-job-that-does-simple-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1.
        run: echo "Step1. Print something out - This job is automatically triggered by a push event."

      - name: Step 2.
        run: echo "Another example of a step"

      - name: Step3. Check out repository code
        uses: actions/checkout@v3

      - name: Step 4.
      - run: echo "The repository has been cloned to the runner."

      - name: List files in the repository
        run: ls

      - name: Step 5.
        run: echo "Job is finished."